import { User, TableSchema } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Emma Mitchell',
    email: 'emma.mitchell@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    id: '2',
    name: 'James Wilson',
    email: 'james.wilson@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: '3',
    name: 'Sophia Anderson',
    email: 'sophia.anderson@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: '4',
    name: 'Lucas Thomas',
    email: 'lucas.thomas@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    id: '5',
    name: 'Olivia Garcia',
    email: 'olivia.garcia@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    id: '6',
    name: 'Benjamin Taylor',
    email: 'benjamin.taylor@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: '7',
    name: 'Ava Martinez',
    email: 'ava.martinez@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: '8',
    name: 'William Johnson',
    email: 'william.johnson@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    id: '9',
    name: 'Mia Robinson',
    email: 'mia.robinson@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
  },
  {
    id: '10',
    name: 'Henry Thompson',
    email: 'henry.thompson@email.com',
    avatarUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
];

export const table1: TableSchema = {
  columns: [
    { accessorKey: 'ID', type: 'link', label: 'ID', editable: false },
    { accessorKey: 'Plasmid', type: 'tag', label: 'Plasmid', editable: false },
    {
      accessorKey: 'VolumeUI',
      type: 'number',
      label: 'Volume (µL)',
      editable: false,
    },
    {
      accessorKey: 'LengthBP',
      type: 'number',
      label: 'Length (bp)',
      editable: false,
    },
    {
      accessorKey: 'StorageLocation',
      type: 'text',
      label: 'Storage Location',
      editable: false,
    },
    {
      accessorKey: 'EditedBy',
      type: 'user',
      label: 'Edited By',
      editable: true,
    },
  ],
  rows: [
    {
      ID: { url: '/1', value: 'inv-GT-plasmid-1' },
      Plasmid: 'GT-plasmids-1: lentiCRISPR v2',
      VolumeUI: 50,
      LengthBP: 14873,
      StorageLocation: 'Freezer 2 Box A1',
      EditedBy: [mockUsers[0]],
    },
    {
      ID: { url: '/2', value: 'inv-GT-plasmid-2' },
      Plasmid: 'GT-plasmids-2: psPAX2',
      VolumeUI: 30,
      LengthBP: 10704,
      StorageLocation: 'Freezer 2 Box A2',
      EditedBy: [mockUsers[0]],
    },
    {
      ID: { url: '/3', value: 'inv-GT-plasmid-3' },
      Plasmid: 'GT-plasmids-3: pMD2.G',
      VolumeUI: 40,
      LengthBP: 5820,
      StorageLocation: 'Freezer 2 Box A2',
      EditedBy: [mockUsers[0]],
    },
    {
      ID: { url: '/4', value: 'inv-GT-plasmid-4' },
      Plasmid: 'GT-plasmids-4: CRISPRoff-v2.1',
      VolumeUI: 25,
      LengthBP: 11875,
      StorageLocation: 'Freezer 2 Box B1',
      EditedBy: [mockUsers[2]],
    },
    {
      ID: { url: '/5', value: 'inv-GT-plasmid-5' },
      Plasmid: 'GT-plasmids-5: TETv4',
      VolumeUI: 35,
      LengthBP: 11679,
      StorageLocation: 'Freezer 2 Box A2',
      EditedBy: [],
    },
    {
      ID: { url: '/6', value: 'inv-GT-plasmid-6' },
      Plasmid: 'GT-plasmids-6: pRSV-Rev',
      VolumeUI: 45,
      LengthBP: 4180,
      StorageLocation: 'Freezer 2 Box A1',
      EditedBy: [],
    },
    {
      ID: { url: '/7', value: 'inv-GT-plasmid-7' },
      Plasmid: 'GT-plasmids-7: lentiCRISPR v2',
      VolumeUI: 30,
      LengthBP: 14873,
      StorageLocation: 'Freezer 2 Box B1',
      EditedBy: [],
    },
    {
      ID: { url: '/8', value: 'inv-GT-plasmid-8' },
      Plasmid: 'GT-plasmids-8: pAdDeltaF6',
      VolumeUI: 40,
      LengthBP: 15420,
      StorageLocation: 'Freezer 2 Box A3',
      EditedBy: [],
    },
    {
      ID: { url: '/9', value: 'inv-GT-plasmid-9' },
      Plasmid: 'GT-plasmids-9: pMDLg',
      VolumeUI: 20,
      LengthBP: 8890,
      StorageLocation: 'Freezer 2 Box A1',
      EditedBy: [],
    },
    {
      ID: { url: '/10', value: 'inv-GT-plasmid-10' },
      Plasmid: 'GT-plasmids-10: pcDNA-3xHA-hTERT',
      VolumeUI: 50,
      LengthBP: 9027,
      StorageLocation: 'Freezer 2 Box A3',
      EditedBy: [],
    },
  ],
};

export const table2: TableSchema = {
  columns: [
    { accessorKey: 'ID', type: 'link', label: 'ID', editable: false },
    { accessorKey: 'Summary', type: 'text', label: 'Summary', editable: false },
    { accessorKey: 'Status', type: 'tag', label: 'Status', editable: false },
    {
      accessorKey: 'Assignee',
      type: 'user',
      label: 'Assignee',
      editable: true,
    },
  ],
  rows: [
    {
      ID: { url: '/tasks/KT-1', value: 'KT-1' },
      Summary: 'Add pka formula',
      Status: 'todo',
      Assignee: [mockUsers[0]],
    },
    {
      ID: { url: '/tasks/KT-2', value: 'KT-2' },
      Summary: 'Select option ordering',
      Status: 'todo',
      Assignee: [mockUsers[1]],
    },
    {
      ID: { url: '/tasks/KT-3', value: 'KT-3' },
      Summary: 'Database filtering v2',
      Status: 'in-progress',
      Assignee: [mockUsers[0], mockUsers[1]],
    },
    {
      ID: { url: '/tasks/KT-4', value: 'KT-4' },
      Summary: 'Colored labels for select',
      Status: 'todo',
      Assignee: [mockUsers[2]],
    },
    {
      ID: { url: '/tasks/KT-5', value: 'KT-5' },
      Summary: 'Default values for select columns',
      Status: 'todo',
      Assignee: [mockUsers[2], mockUsers[3], mockUsers[4]],
    },
    {
      ID: { url: '/tasks/KT-6', value: 'KT-6' },
      Summary: 'Improve UI responsiveness',
      Status: 'in-progress',
      Assignee: [mockUsers[3]],
    },
    {
      ID: { url: '/tasks/KT-7', value: 'KT-7' },
      Summary: 'Update dependencies',
      Status: 'completed',
      Assignee: [mockUsers[6]],
    },
    {
      ID: { url: '/tasks/KT-8', value: 'KT-8' },
      Summary: 'Refactor authentication flow',
      Status: 'todo',
      Assignee: [mockUsers[7]],
    },
    {
      ID: { url: '/tasks/KT-9', value: 'KT-9' },
      Summary: 'Optimize database queries',
      Status: 'in-progress',
      Assignee: [],
    },
    {
      ID: { url: '/tasks/KT-10', value: 'KT-10' },
      Summary: 'Test API error handling',
      Status: 'todo',
      Assignee: [],
    },
  ],
};
